git:
  pagers:
    - pager: delta --paging=never --hunk-header-style=omit --file-style=omit --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      colorArg: never

# initialize a new repo when opening Lazygit outside of a git repo
notARepository: create

gui:
  border: single
  scrollHeight: 5
  showFileIcons: false
  showFileTree: false
  tabWidth: 2
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"

quitOnTopLevelReturn: true

customCommands:
  - key: "t"
    context: "localBranches"
    description: "Trim local branches whose remotes are gone from upstream"
    command: >
      git fetch --prune &&
      git for-each-ref --format '%(refname:short) %(upstream:track)' refs/heads |
      grep '\[gone\]' |
      cut -d' ' -f1 |
      xargs -r git branch -D
