git:
  pagers:
    - pager: delta --paging=never --hunk-header-style=omit --file-style=omit --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      colorArg: never

gui:
  border: single
  scrollHeight: 5
  showFileIcons: false
  showFileTree: false
  tabWidth: 2
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"

quitOnTopLevelReturn: true

customCommands:
  - key: "G"
    command: "gh pr view --repo $(git remote get-url origin) -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Open Github PR in browser"
  - key: "G"
    command: "gh pr view --repo $(git remote get-url origin) -w"
    context: "commits"
    description: "Open Github PR in browser"
  - key: "x"
    context: "localBranches"
    description: "Open branch in browser"
    command: "gh repo view --web --branch {{.SelectedLocalBranch.Name}} $(git remote get-url origin)"
  - key: "x"
    context: "remoteBranches"
    description: "Open branch in browser"
    command: "gh repo view --web --branch {{.SelectedRemoteBranch.Name}} $(git remote get-url upstream)"
  - key: "<c-x>"
    context: "global"
    description: "Open remote in browser"
    command: |
      url=$(git remote get-url origin 2>/dev/null)
      if [ -n "$url" ]; then
          open "$url"
      else
          echo 'no remote found'
      fi
