git:
  pagers:
    - pager: delta --paging=never --hunk-header-style=omit --file-style=omit --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      colorArg: never

gui:
  border: single
  scrollHeight: 5
  showFileIcons: false
  showFileTree: false
  tabWidth: 2
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"

quitOnTopLevelReturn: true

# When working with forks, set the default repo
# using `gh repo set-default` for these to work
customCommands:
  - key: "v"
    context: "localBranches"
    loadingText: "Checking out GitHub Pull Request..."
    command: "gh pr checkout {{.Form.PullRequestNumber}}"
    prompts:
      - type: "menuFromCommand"
        title: "Which PR do you want to check out?"
        key: "PullRequestNumber"
        command: |-
          gh pr list --json number,title,headRefName --template '{{`{{range .}}{{printf "#%v: %s - %s" .number .title .headRefName}}
          {{end}}`}}'
        filter: "#(?P<number>[0-9]+): (?P<title>.+) - (?P<ref_name>[^ ]+)"
        valueFormat: "{{.number}}"
        labelFormat: '{{"#" | black | bold}}{{.number | white | bold}} {{.title | yellow | bold}}{{" [" | black | bold}}{{.ref_name | green}}{{"]" | black | bold}}'
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Open Github PR in browser"
  - key: "G"
    command: "gh pr view -w"
    context: "commits"
    description: "Open Github PR in browser"
  - key: "x"
    command: "gh repo view --web --branch {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Open branch in browser"
  - key: "x"
    command: "gh repo view --web --branch {{.SelectedRemoteBranch.Name}}"
    context: "remoteBranches"
    description: "Open branch in browser"
