git:
  pagers:
    - pager: delta --paging=never --hunk-header-style=omit --file-style=omit --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      colorArg: never

gui:
  border: single
  scrollHeight: 5
  showFileIcons: false
  showFileTree: false
  tabWidth: 2
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"

quitOnTopLevelReturn: true

customCommands:
  - key: "<c-x>"
    context: "global"
    description: "Open remote in browser"
    command: |
      url=$(git remote get-url origin 2>/dev/null)
      if [ -n "$url" ]; then
          open "$url"
      else
          echo 'no remote found'
      fi
